spring:
  application:
    name: wsdlutilidad-api
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    name: wsdlutilidad-microservice
    url: jdbc:h2:file:./build/h2db/db/wsdlutilidad-microservice;DB_CLOSE_DELAY=-1
  rabbitmq:
    host: localhost
    port: 5672
    connection-timeout: 6000

server:
  port: 7000
  servlet:
    context-path: /wsdlutilidad
logging:
  level:
    com.jfacplay: DEBUG
wsdlutilidadconf:
  file : indexer.json
  log:
    urlLog: http://jfacplay/wsMonitoreo/wsMonitoreo.asmx
    idApp: 44
    usr: jfacplay
    ip: 0.0.0.0
  wsdlutilidad:
    endpoint: https://webserverphp.000webhostapp.com/webservices/archivojson.php
